In [11]:
import torch
import glob
import os

In [12]:
saved_models_path = './checkpoints/saved_model_epoch'
models_list = glob.glob(saved_models_path+'*')
models_list.sort(key=os.path.getmtime)
print(models_list)

['./checkpoints/saved_model_epoch0.pth', './checkpoints/saved_model_epoch100.pth']


In [13]:
for model in models_list:
    model = torch.load(model)
    print(model['linear.weight'][0][:5])
    print(model['linear.bias'])

tensor([-0.0021,  0.0001, -0.0386, -0.0679, -0.0673], device='cuda:0')
tensor([0.1501], device='cuda:0')
tensor([-2.0783e-03,  1.3069e-04,  1.2060e+00, -6.7888e-02, -6.7277e-02],
       device='cuda:0')
tensor([1.3244], device='cuda:0')


In [14]:
for model in models_list:
    model = torch.load(model)
    print(model['lstm.layers.0.cell.weight_hh'].shape)
    print(model['lstm.layers.0.cell.bias_hh'][:5])

torch.Size([200, 50])
tensor([ 0.5970,  0.0850, -0.0312,  1.9651, -0.3852], device='cuda:0')
torch.Size([200, 50])
tensor([ 0.5970,  0.0850, -0.0312,  1.9651, -0.3852], device='cuda:0')


In [15]:
for model in models_list:
    model = torch.load(model)
    print(model['lstm.layers.0.cell.weight_ih'][0][:5])
    print(model['lstm.layers.0.cell.bias_ih'][:5])

tensor([-1.1973], device='cuda:0')
tensor([ 2.8148, -1.1872,  0.4096, -0.2309,  0.5410], device='cuda:0')
tensor([-1.1973], device='cuda:0')
tensor([ 2.8148, -1.1872,  0.4096, -0.2309,  0.5410], device='cuda:0')


In [16]:
for model in models_list:
    model = torch.load(model)
    print(model['lstm.layers.0.cell.sigma.sigma'].mean())
    print(model['lstm.layers.0.cell.sigma.sigma'][:])

tensor(0.4952, device='cuda:0')
tensor([0.5763, 0.5082, 0.4992, 0.5639, 0.3336, 0.4819, 0.5951, 0.6409, 0.4286,
        0.5440, 0.4452, 0.5965, 0.4411, 0.4369, 0.3825, 0.3911, 0.5022, 0.5593,
        0.5523, 0.7044, 0.5711, 0.4556, 0.3360, 0.5981, 0.5212, 0.4609, 0.2429,
        0.5500, 0.5723, 0.5717, 0.4314, 0.5924, 0.4818, 0.4151, 0.2570, 0.6048,
        0.3599, 0.4408, 0.4180, 0.6082, 0.5513, 0.5362, 0.4246, 0.4672, 0.2777,
        0.5238, 0.4859, 0.4958, 0.7805, 0.5289, 0.6631, 0.3630, 0.3687, 0.3674,
        0.4624, 0.4962, 0.5618, 0.4715, 0.4927, 0.4690, 0.3351, 0.3862, 0.3692,
        0.4188, 0.4210, 0.5643, 0.7965, 0.4145, 0.5414, 0.5160, 0.5109, 0.7982,
        0.4923, 0.3888, 0.4934, 0.4887, 0.5399, 0.5320, 0.6791, 0.5106, 0.3435,
        0.5563, 0.2640, 0.6487, 0.5945, 0.3433, 0.5393, 0.3985, 0.5205, 0.4595,
        0.6206, 0.5837, 0.4626, 0.4843, 0.4997, 0.4850, 0.5837, 0.6019, 0.4370,
        0.4567, 0.4113, 0.5128, 0.5162, 0.5992, 0.4205, 0.3547, 0.3826, 0.6181,
        

In [17]:
for key in model.keys():
    print(key)

lstm.layers.0.cell.weight_ih
lstm.layers.0.cell.weight_hh
lstm.layers.0.cell.bias_ih
lstm.layers.0.cell.bias_hh
lstm.layers.0.cell.sigma.sigma
linear.weight
linear.bias
