In [1]:
import torch
import glob
import os

In [2]:
saved_models_path = './checkpoints/saved_model_epoch'
models_list = glob.glob(saved_models_path+'*')
models_list.sort(key=os.path.getmtime)
print(models_list)

['./checkpoints/saved_model_epoch0.pth', './checkpoints/saved_model_epoch100.pth']


In [5]:
for model in models_list:
    model = torch.load(model)
    print(model['linear.weight'])
    print(model['linear.bias'])

tensor([[-0.1103,  0.0442,  0.1060, -0.0102,  0.0666,  0.1098,  0.1175,  0.0078,
          0.0355, -0.0794,  0.1291, -0.0788,  0.0333, -0.0146, -0.0309,  0.0596,
         -0.1001,  0.1132,  0.0813,  0.1022,  0.0215,  0.0572, -0.0491, -0.0411,
          0.1323,  0.0279,  0.0299,  0.1137,  0.0393,  0.1240, -0.0208, -0.0397,
         -0.1253, -0.0532,  0.0573,  0.0500,  0.1399, -0.0557,  0.0683,  0.0300,
         -0.0553, -0.0817, -0.0346, -0.0491, -0.0975,  0.0469,  0.0659,  0.0537,
         -0.0180, -0.0762]], device='cuda:0')
tensor([-0.0159], device='cuda:0')
tensor([[-1.2767,  1.2104,  0.1060, -0.0102,  0.0666,  0.1098,  0.1175,  0.0078,
         -1.1307, -0.0342,  0.1291, -0.0788,  0.0333, -1.4318, -0.0265,  0.0133,
          1.0663,  0.1132, -1.0850,  0.0560,  0.0215, -1.1093, -0.0491, -1.2073,
          1.2987,  0.0279, -1.1364, -1.0527,  0.0393,  0.1240, -1.1872, -1.2061,
         -0.1253, -0.0532,  0.0573,  1.4459,  0.1399, -1.5242,  0.0683,  0.0300,
          1.1111, -0.0817, -

In [11]:
for model in models_list:
    model = torch.load(model)
    print(model['lstm.layers.0.cell.weight_hh'].shape)
    print(model['lstm.layers.0.cell.bias_hh'][:5])

torch.Size([200, 50])
tensor([0.2793, 0.6906, 1.8314, 0.0217, 1.8791], device='cuda:0')
torch.Size([200, 50])
tensor([0.2793, 0.6906, 1.8314, 0.0217, 1.8791], device='cuda:0')


In [7]:
for model in models_list:
    model = torch.load(model)
    print(model['lstm.layers.0.cell.weight_ih'].shape)
    print(model['lstm.layers.0.cell.bias_ih'][:5])

torch.Size([200, 1])
tensor([-0.6226,  0.3253,  1.3542,  1.3133,  0.4896], device='cuda:0')
torch.Size([200, 1])
tensor([-0.6226,  0.3253,  1.3542,  1.3133,  0.4896], device='cuda:0')


In [8]:
for model in models_list:
    model = torch.load(model)
    print(model['lstm.layers.0.cell.sigma.sigma'].shape)
    print(model['lstm.layers.0.cell.sigma.sigma'][:])

torch.Size([200])
tensor([0.6300, 0.6169, 0.4210, 0.5093, 0.3645, 0.5968, 0.5033, 0.5871, 0.5910,
        0.5505, 0.4594, 0.4710, 0.5362, 0.4965, 0.6227, 0.5304, 0.4938, 0.4106,
        0.6803, 0.4381, 0.4281, 0.5100, 0.4234, 0.5694, 0.4113, 0.4503, 0.5601,
        0.6590, 0.6553, 0.2684, 0.4627, 0.4416, 0.4187, 0.6335, 0.3663, 0.4647,
        0.4933, 0.4005, 0.4835, 0.4330, 0.5961, 0.5443, 0.5433, 0.5453, 0.5497,
        0.4004, 0.5098, 0.4623, 0.4883, 0.4263, 0.3205, 0.6427, 0.4466, 0.5488,
        0.5663, 0.3592, 0.3944, 0.4643, 0.5190, 0.4754, 0.7099, 0.4934, 0.4429,
        0.3892, 0.3871, 0.5876, 0.4527, 0.6247, 0.5264, 0.4497, 0.4930, 0.3916,
        0.4017, 0.4804, 0.7476, 0.3623, 0.6178, 0.5265, 0.2709, 0.5260, 0.5479,
        0.6188, 0.5044, 0.6252, 0.6146, 0.6015, 0.6218, 0.5817, 0.4549, 0.4821,
        0.2860, 0.4258, 0.6877, 0.5583, 0.6416, 0.5633, 0.4051, 0.4089, 0.3829,
        0.5725, 0.4893, 0.6168, 0.4539, 0.6725, 0.3909, 0.4281, 0.5646, 0.7028,
        0.4796, 0.3990

In [17]:
for key in model.keys():
    print(key)

lstm.layers.0.cell.weight_ih
lstm.layers.0.cell.weight_hh
lstm.layers.0.cell.bias_ih
lstm.layers.0.cell.bias_hh
lstm.layers.0.cell.sigma.sigma
linear.weight
linear.bias
