In [1]:
import torch
import glob
import os

In [31]:
saved_models_path = './checkpoints/saved_model_epoch'
models_list = glob.glob(saved_models_path+'*')
models_list.sort(key=os.path.getmtime)
print(models_list)

['./checkpoints/saved_model_epoch0.pth', './checkpoints/saved_model_epoch100.pth']


In [42]:
for model in models_list:
    model = torch.load(model)
    print(model['linear.weight'][0][:5])
    print(model['linear.bias'])

tensor([-0.0970, -0.0083,  0.0431,  0.0008, -0.1135], device='cuda:0')
tensor([-0.0818], device='cuda:0')
tensor([-9.6985e-02,  1.1690e+00,  4.3278e-02,  8.1026e-04, -1.1354e-01],
       device='cuda:0')
tensor([1.0956], device='cuda:0')


In [46]:
for model in models_list:
    model = torch.load(model)
    print(model['lstm.layers.0.cell.weight_hh'].shape)
    print(model['lstm.layers.0.cell.bias_hh'][:5])

torch.Size([200, 50])
tensor([-1.0262,  0.2853,  0.3087, -0.5944,  0.2000], device='cuda:0')
torch.Size([200, 50])
tensor([-1.0262,  0.2853,  0.3087, -0.5944,  0.2000], device='cuda:0')


In [ ]:
for model in models_list:
    model = torch.load(model)
    print(model['lstm.layers.0.cell.weight_ih'][0][:5])
    print(model['lstm.layers.0.cell.bias_ih'][:5])

In [ ]:
for model in models_list:
    model = torch.load(model)
    print(model['lstm.layers.0.cell.sigma.sigma'].mean())
    print(model['lstm.layers.0.cell.sigma.sigma'][:5])

In [4]:
for key in model.keys():
    print(key)

lstm.layers.0.cell.weight_ih
lstm.layers.0.cell.weight_hh
lstm.layers.0.cell.bias_ih
lstm.layers.0.cell.bias_hh
lstm.layers.0.cell.sigma.sigma
linear.weight
linear.bias
