In [12]:
import torch
import glob
import os

In [13]:
saved_models_path = './checkpoints/saved_model_epoch'
models_list = glob.glob(saved_models_path+'*')
models_list.sort(key=os.path.getmtime)
print(models_list)

['./checkpoints/saved_model_epoch0.pth', './checkpoints/saved_model_epoch100.pth']


In [14]:
for model in models_list:
    model = torch.load(model)
    print(model['linear.weight'])
    print(model['linear.bias'])

tensor([[ 5.0913e-02,  1.4111e-01,  1.9981e-02,  1.2530e-02,  7.3537e-02,
         -1.3951e-01,  5.2015e-02,  8.7289e-03, -6.3487e-02,  7.6948e-02,
         -6.4772e-02, -1.3679e-01,  3.3600e-02, -1.1989e-01, -2.8561e-02,
         -7.3896e-02, -2.8639e-02,  1.0504e-01,  1.0747e-01, -8.4895e-02,
          6.1581e-02,  6.2465e-02, -4.1712e-02, -3.9643e-03, -2.2466e-02,
         -1.3500e-01,  1.1248e-04, -2.8022e-02, -1.2851e-01,  2.5459e-02,
         -1.3393e-01,  8.2915e-02,  8.0746e-02,  1.1805e-02, -1.1402e-01,
         -1.2353e-01,  4.7708e-02, -6.5319e-02,  4.3008e-02,  2.9461e-02,
         -6.9310e-02,  1.1745e-01,  2.1195e-02,  4.5903e-02, -1.2707e-01,
         -9.6914e-02, -3.3705e-02, -1.2159e-01, -8.0227e-02,  2.5234e-02]],
       device='cuda:0')
tensor([0.0994], device='cuda:0')
tensor([[ 0.0509,  0.1411,  0.0200,  0.0125,  0.0735, -1.5867,  0.0520,  0.0087,
         -0.0635, -1.0913, -0.0648, -0.1368, -1.2036, -1.4516, -1.1968, -0.0739,
         -1.1967,  1.2733,  0.1075, -0

In [15]:
for model in models_list:
    model = torch.load(model)
    print(model['lstm.layers.0.cell.weight_hh'].shape)
    print(model['lstm.layers.0.cell.bias_hh'][:5])

torch.Size([200, 50])
tensor([ 0.1946, -0.9194,  1.2180, -0.8793, -0.3434], device='cuda:0')
torch.Size([200, 50])
tensor([ 0.1946, -0.9194,  1.2180, -0.8793, -0.3434], device='cuda:0')


In [16]:
for model in models_list:
    model = torch.load(model)
    print(model['lstm.layers.0.cell.weight_ih'].shape)
    print(model['lstm.layers.0.cell.bias_ih'][:5])

torch.Size([200, 1])
tensor([-0.1105, -0.6263, -0.1871, -0.3292, -0.3255], device='cuda:0')
torch.Size([200, 1])
tensor([-0.1105, -0.6263, -0.1871, -0.3292, -0.3255], device='cuda:0')


In [17]:
for model in models_list:
    model = torch.load(model)
    print(model['lstm.layers.0.cell.sigma.sigma'].shape)
    print(model['lstm.layers.0.cell.sigma.sigma'][:])

torch.Size([200])
tensor([0.3852, 0.5836, 0.5212, 0.4179, 0.3603, 0.3830, 0.4230, 0.5351, 0.3930,
        0.4495, 0.4866, 0.4437, 0.5145, 0.4264, 0.4522, 0.3894, 0.4772, 0.4592,
        0.7066, 0.3982, 0.4630, 0.5679, 0.4793, 0.5285, 0.4025, 0.3681, 0.4514,
        0.5405, 0.5325, 0.4058, 0.5234, 0.3870, 0.3748, 0.4952, 0.4139, 0.6125,
        0.5002, 0.5608, 0.4011, 0.3851, 0.4375, 0.4842, 0.3620, 0.6241, 0.5329,
        0.5329, 0.4140, 0.5137, 0.3099, 0.6394, 0.6847, 0.5375, 0.6600, 0.5353,
        0.3045, 0.5034, 0.5596, 0.6170, 0.4949, 0.6968, 0.6684, 0.5729, 0.4594,
        0.6044, 0.5843, 0.4953, 0.4341, 0.5914, 0.3589, 0.5090, 0.5629, 0.4665,
        0.4084, 0.4538, 0.5975, 0.3338, 0.6334, 0.4798, 0.6081, 0.4771, 0.6371,
        0.5322, 0.5747, 0.4423, 0.4746, 0.4627, 0.4757, 0.6401, 0.4538, 0.7614,
        0.4890, 0.5826, 0.4912, 0.4188, 0.4319, 0.4450, 0.3476, 0.5610, 0.5650,
        0.3909, 0.6368, 0.6626, 0.6387, 0.5464, 0.4864, 0.7463, 0.6716, 0.6546,
        0.6397, 0.4610

In [18]:
for key in model.keys():
    print(key)

lstm.layers.0.cell.weight_ih
lstm.layers.0.cell.weight_hh
lstm.layers.0.cell.bias_ih
lstm.layers.0.cell.bias_hh
lstm.layers.0.cell.sigma.sigma
linear.weight
linear.bias
