In [1]:
import torch
import glob
import os

In [2]:
saved_models_path = './checkpoints/saved_model_epoch'
models_list = glob.glob(saved_models_path+'*')
models_list.sort(key=os.path.getmtime)
#print(models_list)

In [3]:
model = torch.load(models_list[0])
print(model['_orig_mod.lstm.layers.0.cell.sigma.sigma'].shape)
print(model.keys())
for model in models_list:
    model = torch.load(model)
    if '_orig_mod.lstm.layers.0.cell.sigma.mu' in model:
        print('mean mu:',f'{model['_orig_mod.lstm.layers.0.cell.sigma.mu'].mean().item():.4f}')
        print('std mu:',f'{model['_orig_mod.lstm.layers.0.cell.sigma.mu'].std().item():.4f}')
    print('mean sigma:',f'{model['_orig_mod.lstm.layers.0.cell.sigma.sigma'].mean().item():.4f}')
    print('std sigma:',f'{model['_orig_mod.lstm.layers.0.cell.sigma.sigma'].std().item():.4f}')
    print('--------------------------')
    #print(model['_orig_mod.lstm.layers.0.cell.sigma.sigma'][:])

torch.Size([2000])
odict_keys(['_orig_mod.lstm.layers.0.cell.weight_ih', '_orig_mod.lstm.layers.0.cell.weight_hh', '_orig_mod.lstm.layers.0.cell.bias_ih', '_orig_mod.lstm.layers.0.cell.bias_hh', '_orig_mod.lstm.layers.0.cell.sigma.sigma', '_orig_mod.linear.weight', '_orig_mod.linear.bias'])
mean sigma: 0.2488
std sigma: 0.0487
--------------------------
mean sigma: 0.2473
std sigma: 0.0508
--------------------------


In [4]:
for model in models_list:
    model = torch.load(model)
    print(model['_orig_mod.lstm.layers.0.cell.weight_hh'].shape)
    print(model['_orig_mod.lstm.layers.0.cell.bias_hh'][:5])

torch.Size([2000, 500])
tensor([-2.0841,  1.9260,  0.3573, -1.1646, -1.5593])
torch.Size([2000, 500])
tensor([-2.0841,  1.9260,  0.3459, -1.1646, -1.5593])


In [5]:
for model in models_list:
    model = torch.load(model)
    print(model['_orig_mod.lstm.layers.0.cell.weight_ih'].shape)
    print(model['_orig_mod.lstm.layers.0.cell.bias_ih'][:5])

torch.Size([2000, 1])
tensor([-0.4198, -0.9840, -1.0608, -0.7250, -0.8990])
torch.Size([2000, 1])
tensor([-0.4198, -0.9840, -1.0721, -0.7250, -0.8990])


In [6]:
'''
for model in models_list:
    model = torch.load(model)
    print(model['_orig_mod.linear.weight'])
    print(model['_orig_mod.linear.bias'])
''';

In [7]:
dict1 = {'a': 1, 'b': 2}
dict2 = {'a': 3, 'b': 4}
dict3 = {'dict1':dict1, 'dict2':dict2}
dict4 = dict3.get('dict1',{})
print(dict4)
dict5 = dict3['dict1']
print(dict5)
if 'f' in dict5:
    print('pozí')
else:
    print('ponó')

{'a': 1, 'b': 2}
{'a': 1, 'b': 2}
ponó
