In [8]:
import torch
import glob
import os

In [9]:
saved_models_path = './checkpoints/saved_model_epoch'
models_list = glob.glob(saved_models_path+'*')
models_list.sort(key=os.path.getmtime)
#print(models_list)

In [10]:
model = torch.load(models_list[0])
print(model['_orig_mod.lstm.layers.0.cell.sigma.sigma'].shape)
print(model.keys())
for model in models_list:
    model = torch.load(model)
    if '_orig_mod.lstm.layers.0.cell.sigma.mu' in model:
        print('mean mu:',f'{model['_orig_mod.lstm.layers.0.cell.sigma.mu'].mean().item():.4f}')
        print('std mu:',f'{model['_orig_mod.lstm.layers.0.cell.sigma.mu'].std().item():.4f}')
    print('mean sigma:',f'{model['_orig_mod.lstm.layers.0.cell.sigma.sigma'].mean().item():.4f}')
    print('std sigma:',f'{model['_orig_mod.lstm.layers.0.cell.sigma.sigma'].std().item():.4f}')
    print('--------------------------')
    #print(model['_orig_mod.lstm.layers.0.cell.sigma.sigma'][:])

torch.Size([2000])
odict_keys(['_orig_mod.lstm.layers.0.cell.weight_ih', '_orig_mod.lstm.layers.0.cell.weight_hh', '_orig_mod.lstm.layers.0.cell.bias_ih', '_orig_mod.lstm.layers.0.cell.bias_hh', '_orig_mod.lstm.layers.0.cell.sigma.sigma', '_orig_mod.linear.weight', '_orig_mod.linear.bias'])
mean sigma: 0.2469
std sigma: 0.0513
--------------------------
mean sigma: 0.2438
std sigma: 0.0554
--------------------------
mean sigma: 0.2355
std sigma: 0.0708
--------------------------
mean sigma: 0.2309
std sigma: 0.0784
--------------------------
mean sigma: 0.2287
std sigma: 0.0807
--------------------------
mean sigma: 0.2282
std sigma: 0.0823
--------------------------
mean sigma: 0.2280
std sigma: 0.0830
--------------------------
mean sigma: 0.2280
std sigma: 0.0825
--------------------------
mean sigma: 0.2275
std sigma: 0.0833
--------------------------
mean sigma: 0.2271
std sigma: 0.0836
--------------------------
mean sigma: 0.2271
std sigma: 0.0834
--------------------------
mean

In [11]:
for model in models_list:
    model = torch.load(model)
    print(model['_orig_mod.lstm.layers.0.cell.weight_hh'].shape)
    print(model['_orig_mod.lstm.layers.0.cell.bias_hh'][:5])

torch.Size([2000, 500])
tensor([-1.7190,  2.6082, -0.4977,  0.0155,  0.7085])
torch.Size([2000, 500])
tensor([-1.7190,  2.6082, -0.4977,  0.0155,  0.7085])
torch.Size([2000, 500])
tensor([-1.7190,  2.6082, -0.4977,  0.0155,  0.7085])
torch.Size([2000, 500])
tensor([-1.7191,  2.6082, -0.4977,  0.0155,  0.7085])
torch.Size([2000, 500])
tensor([-1.7191,  2.6082, -0.4977,  0.0155,  0.7085])
torch.Size([2000, 500])
tensor([-1.7191,  2.6082, -0.4977,  0.0155,  0.7085])
torch.Size([2000, 500])
tensor([-1.7191,  2.6082, -0.4977,  0.0155,  0.7085])
torch.Size([2000, 500])
tensor([-1.7191,  2.6082, -0.4977,  0.0155,  0.7085])
torch.Size([2000, 500])
tensor([-1.7191,  2.6082, -0.4977,  0.0155,  0.7085])
torch.Size([2000, 500])
tensor([-1.7191,  2.6082, -0.4977,  0.0155,  0.7085])
torch.Size([2000, 500])
tensor([-1.7191,  2.6082, -0.4977,  0.0155,  0.7085])
torch.Size([2000, 500])
tensor([-1.7191,  2.6082, -0.4977,  0.0155,  0.7085])
torch.Size([2000, 500])
tensor([-1.7191,  2.6082, -0.4977,  0.01

In [12]:
for model in models_list:
    model = torch.load(model)
    print(model['_orig_mod.lstm.layers.0.cell.weight_ih'].shape)
    print(model['_orig_mod.lstm.layers.0.cell.bias_ih'][:5])

torch.Size([2000, 1])
tensor([-1.5588,  0.1184, -1.5963,  1.0367,  1.0166])
torch.Size([2000, 1])
tensor([-1.5588,  0.1184, -1.5963,  1.0367,  1.0166])
torch.Size([2000, 1])
tensor([-1.5588,  0.1184, -1.5963,  1.0367,  1.0166])
torch.Size([2000, 1])
tensor([-1.5589,  0.1184, -1.5963,  1.0367,  1.0166])
torch.Size([2000, 1])
tensor([-1.5589,  0.1184, -1.5963,  1.0367,  1.0166])
torch.Size([2000, 1])
tensor([-1.5589,  0.1184, -1.5963,  1.0367,  1.0166])
torch.Size([2000, 1])
tensor([-1.5589,  0.1184, -1.5963,  1.0367,  1.0166])
torch.Size([2000, 1])
tensor([-1.5589,  0.1184, -1.5963,  1.0367,  1.0166])
torch.Size([2000, 1])
tensor([-1.5589,  0.1184, -1.5963,  1.0367,  1.0166])
torch.Size([2000, 1])
tensor([-1.5589,  0.1184, -1.5963,  1.0367,  1.0166])
torch.Size([2000, 1])
tensor([-1.5589,  0.1184, -1.5963,  1.0367,  1.0166])
torch.Size([2000, 1])
tensor([-1.5589,  0.1184, -1.5963,  1.0367,  1.0166])
torch.Size([2000, 1])
tensor([-1.5589,  0.1184, -1.5963,  1.0367,  1.0166])
torch.Size([

In [13]:
'''
for model in models_list:
    model = torch.load(model)
    print(model['_orig_mod.linear.weight'])
    print(model['_orig_mod.linear.bias'])
''';

In [14]:
dict1 = {'a': 1, 'b': 2}
dict2 = {'a': 3, 'b': 4}
dict3 = {'dict1':dict1, 'dict2':dict2}
dict4 = dict3.get('dict1',{})
print(dict4)
dict5 = dict3['dict1']
print(dict5)
if 'f' in dict5:
    print('pozí')
else:
    print('ponó')

{'a': 1, 'b': 2}
{'a': 1, 'b': 2}
ponó
